version: "3.6"

services:
  app:
    container_name: go-challenge
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app

  mongodb:
    container_name: mongodb
    image: "mongo:3.6.2"
    ports:
      - 27017:27017
    volumes:
      - ./script/mongodb:/docker-entrypoint-initdb.d